# Trained on data from the 2018 Kaggle Data Science Bowl: https://www.kaggle.com/c/data-science-bowl-2018/data
model:
  name: UNet2D
  in_channels: 3
  out_channels: 1
  layer_order: cr
  f_maps: [32, 64, 128]
  final_sigmoid: true
  is_segmentation: true
trainer:
  checkpoint_dir: PATH_TO_CHECKPOINT_DIR
  resume: null
  pre_trained: null
  validate_after_iters: 250
  log_after_iters: 250
  max_num_epochs: 10000
  max_num_iterations: 150000
  eval_score_higher_is_better: True
optimizer:
  learning_rate: 0.0002
  weight_decay: 0.00001
loss:
  name: DiceLoss
  skip_last_target: true
eval_metric:
  name: BlobsAveragePrecision
  use_last_target: true
  metric: 'ap'
lr_scheduler:
  name: ReduceLROnPlateau
  mode: max
  factor: 0.2
  patience: 30
loaders:
  dataset: LazyHDF5Dataset
  batch_size: 16
  num_workers: 8
  train:
    file_paths:
      - PATH_TO_TRAIN_DIR

    transformer:
      raw:
        - name: ToTensor
          expand_dims: true
      label:
        - name: ToTensor
          expand_dims: true
  val:
    file_paths:
      - PATH_TO_VAL_DIR

    transformer:
      raw:
        - name: ToTensor
          expand_dims: true
      label:
        - name: ToTensor
          expand_dims: true